language: node_js

node_js:
  - "6"

services:
  - mongodb

before_script:
  - sleep 10
  - mongod --version

script:
  - npm run verify

notifications:
  email:
    on_success: change
    on_failure: change
