language: node_js

node_js:
  - "6"

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_install:
  - mongod --version

script:
  - npm run verify

notifications:
  email:
    on_success: change
    on_failure: change
